-- AlterTable
ALTER TABLE `POKEMON` MODIFY `DESCRIPTION_EN` TEXT NOT NULL,
    MODIFY `DESCRIPTION_FR` TEXT NOT NULL;

-- AlterTable
ALTER TABLE `TALENT` MODIFY `DESCRIPTION_EN` TEXT NOT NULL,
    MODIFY `DESCRIPTION_FR` TEXT NOT NULL;
