-- CreateTable
CREATE TABLE `Pokemon` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `POKEMON_ID` INTEGER NOT NULL,
    `NAME` JSON NOT NULL,
    `GENERATION` INTEGER NOT NULL,
    `INFORMATIONS` JSON NOT NULL,
    `STATISTICS` JSON NOT NULL,
    `EVOLUTION` INTEGER NULL DEFAULT -1,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Pokemon_POKEMON_ID_key`(`POKEMON_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Informations` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `HEIGHT` VARCHAR(191) NOT NULL,
    `CATEGORY` VARCHAR(191) NOT NULL,
    `WEIGHT` VARCHAR(191) NOT NULL,
    `TYPE` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Sprites` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `URL` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LASTNAME` VARCHAR(191) NOT NULL,
    `FIRSTNAME` VARCHAR(191) NOT NULL,
    `EMAIL` VARCHAR(191) NOT NULL,
    `PASSWORD` VARCHAR(191) NOT NULL,
    `USERNAME` VARCHAR(191) NOT NULL,
    `UUID` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Generation` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `DESCRIPTION` VARCHAR(191) NOT NULL,
    `MIN` INTEGER NOT NULL DEFAULT 0,
    `MAX` INTEGER NOT NULL DEFAULT 1010,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Pokelist` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(191) NOT NULL,
    `IMAGE` VARCHAR(191) NOT NULL,
    `USER_ID` INTEGER NOT NULL,

    INDEX `Pokelist_USER_ID_idx`(`USER_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PokelistData` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `POKEMON_ID` INTEGER NOT NULL,
    `USER_ID` INTEGER NOT NULL,
    `POKELIST_ID` INTEGER NOT NULL,
    `OWNED` INTEGER NOT NULL,
    `NOTE` VARCHAR(191) NOT NULL,

    INDEX `PokelistData_POKEMON_ID_idx`(`POKEMON_ID`),
    INDEX `PokelistData_USER_ID_idx`(`USER_ID`),
    INDEX `PokelistData_POKELIST_ID_idx`(`POKELIST_ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
