-- DropIndex
DROP INDEX `POKEMON_CATEGORY_ID_fkey` ON `POKEMON`;

-- DropIndex
DROP INDEX `POKEMON_SHAPE_ID_fkey` ON `POKEMON`;

-- CreateIndex
CREATE FULLTEXT INDEX `SHAPE_NAME_idx` ON `SHAPE`(`NAME`);

-- CreateIndex
CREATE FULLTEXT INDEX `TYPE_NAME_idx` ON `TYPE`(`NAME`);
