/*
  Warnings:

  - You are about to drop the column `EVOLUTION` on the `POKEMON` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE `POKEMON` DROP COLUMN `EVOLUTION`,
    ADD COLUMN `EVOLUTION_ID` INTEGER NULL DEFAULT -1;

-- CreateTable
CREATE TABLE `EVOLUTION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `GENDER` VARCHAR(191) NOT NULL,
    `HELD_ITEM` VARCHAR(191) NOT NULL,
    `ITEM` VARCHAR(191) NOT NULL,
    `KNOW_MOVE` VARCHAR(191) NOT NULL,
    `KNOW_MOVE_TYPE` VARCHAR(191) NOT NULL,
    `LOCATION` INTEGER NOT NULL,
    `MIN_AFFECTION` INTEGER NOT NULL,
    `MIN_BEAUTY` INTEGER NOT NULL,
    `MIN_HAPPINESS` INTEGER NOT NULL,
    `MIN_LEVEL` INTEGER NOT NULL,
    `NEEDS_OVERWORLDS_RAIN` INTEGER NOT NULL,
    `PARTY_SPECIES` VARCHAR(191) NOT NULL,
    `PARTY_TYPE` VARCHAR(191) NOT NULL,
    `RELATIVE_PHYSICAL_STATS` VARCHAR(191) NOT NULL,
    `TIME_OF_DAY` VARCHAR(191) NOT NULL,
    `TRADE_SPECIES` VARCHAR(191) NOT NULL,
    `TRIGGER` VARCHAR(191) NOT NULL,
    `POKEMON_ID` INTEGER NOT NULL,
    `CHAIN_ID` INTEGER NOT NULL,
    `LEVEL` INTEGER NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
