-- AddForeignKey
ALTER TABLE `Pokelist` ADD CONSTRAINT `Pokelist_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PokelistData` ADD CONSTRAINT `PokelistData_POKEMON_ID_fkey` FOREIGN KEY (`POKEMON_ID`) REFERENCES `Pokemon`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PokelistData` ADD CONSTRAINT `PokelistData_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `User`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PokelistData` ADD CONSTRAINT `PokelistData_POKELIST_ID_fkey` FOREIGN KEY (`POKELIST_ID`) REFERENCES `Pokelist`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
